# Generated by Django 3.2.4 on 2021-07-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogger_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogger',
            old_name='description1',
            new_name='description',
        ),
        migrations.AddField(
            model_name='blogger',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
