# Generated by Django 3.2.4 on 2021-07-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210702_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
